import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { loadCatalog, catalogAsPromptText } from "./blockCatalog.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "generated");

const prompt = process.argv[2];
const dryRun = process.argv.includes("--dry-run");

if (!prompt) {
  console.error(
    'Usage: node generator/generate.mjs "your site prompt" [--dry-run]'
  );
  process.exit(1);
}

const catalog = loadCatalog();

// ---- Step A: decide which blocks to use + how to customize them ----
async function planWithLLM() {
  const system = `You lay out sections for a 3D website from a library of pre-built blocks.
Given the block library and a user's prompt, choose which blocks to use, in what
order, and what props to pass each one. Only use props each block actually defines.
Blocks are placed automatically based on their renderTarget (canvas vs dom) —
you don't need to worry about that, just pick blocks and props.
Respond with ONLY valid JSON, no prose, no markdown fences, in this exact shape:
{ "sections": [ { "block": "<block id>", "props": { } } ] }`;

  const user = `Block library:\n\n${catalogAsPromptText(
    catalog
  )}\n\nUser's site prompt: "${prompt}"`;

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 1000,
      system,
      messages: [{ role: "user", content: user }],
    }),
  });

  if (!res.ok) {
    throw new Error(`Anthropic API error: ${res.status} ${await res.text()}`);
  }

  const data = await res.json();
  const text = data.content.find((b) => b.type === "text")?.text ?? "{}";
  const clean = text.replace(/```json|```/g, "").trim();
  return JSON.parse(clean);
}

// ---- Fallback: a dumb keyword heuristic so you can test the pipeline
// ---- without an API key yet. Replace by removing --dry-run once step 3
// ---- is wired to a real key.
function planWithHeuristic() {
  const lower = prompt.toLowerCase();
  const sections = [];

  if (/particle|atmosphere|ambient|background/.test(lower)) {
    sections.push({ block: "particle-background", props: {} });
  }
  if (/mascot|bunny|icon|logo|character/.test(lower)) {
    sections.push({
      block: "floating-icon",
      props: { rimColor: /coffee|coding/.test(lower) ? "#4fd1ff" : "#7f77dd" },
    });
  }
  sections.push({
    block: "scroll-reveal-section",
    props: { direction: "up" },
  });

  return { sections };
}

// ---- Step B: turn the plan into an actual App.jsx ----
// Blocks are either `canvas` (Three.js objects — must live inside <Canvas>)
// or `dom` (plain HTML/React — must live outside it). Mixing them crashes
// at runtime even though it builds fine, so we split by renderTarget here
// rather than trusting the LLM to get placement right.
function writeGeneratedApp(plan) {
  const resolved = plan.sections
    .map((s) => ({ section: s, block: catalog.find((b) => b.id === s.block) }))
    .filter((r) => r.block);

  const imports = resolved
    .map(
      ({ block }) =>
        `import ${block.component} from "../src/blocks/${block.folder}/${block.component}.jsx";`
    )
    .join("\n");

  const toJsx = ({ section, block }) => {
    const propsStr = Object.entries(section.props ?? {})
      .map(([k, v]) => `${k}={${JSON.stringify(v)}}`)
      .join(" ");
    return `      <${block.component} ${propsStr} />`;
  };

  const canvasSections = resolved
    .filter((r) => r.block.renderTarget !== "dom")
    .map(toJsx)
    .join("\n");
  const domSections = resolved
    .filter((r) => r.block.renderTarget === "dom")
    .map(toJsx)
    .join("\n");

  const appCode = `// AUTO-GENERATED by generator/generate.mjs — prompt was:
// "${prompt}"
import { Canvas } from "@react-three/fiber";
${imports}

export default function App() {
  return (
    <>
      <div style={{ width: "100vw", height: "100vh", position: "fixed", inset: 0, zIndex: 0 }}>
        <Canvas camera={{ position: [0, 0, 6] }}>
${canvasSections}
        </Canvas>
      </div>
      <div style={{ position: "relative", zIndex: 1 }}>
${domSections}
      </div>
    </>
  );
}
`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, "App.jsx"), appCode);
  console.log(`Wrote ${join(OUT_DIR, "App.jsx")}`);
  console.log("\nPlan used:\n", JSON.stringify(plan, null, 2));
}

const plan = dryRun ? planWithHeuristic() : await planWithLLM();
writeGeneratedApp(plan);
