INSERT INTO skills (name, category, proficiency, "order", created_at, updated_at) VALUES
('Docker', 'Cloud & Virtualization', 72, 1, NOW(), NOW()),
('Docker Compose', 'Cloud & Virtualization', 68, 2, NOW(), NOW()),
('Portainer', 'Cloud & Virtualization', 70, 3, NOW(), NOW()),
('Unraid', 'Systems Administration', 74, 1, NOW(), NOW()),
('WordPress', 'Software & Applications', 80, 1, NOW(), NOW()),
('WordPress Multisite', 'Software & Applications', 72, 2, NOW(), NOW()),
('Elementor', 'Software & Applications', 78, 3, NOW(), NOW()),
('Web Hosting', 'Systems Administration', 72, 2, NOW(), NOW()),
('Linux Server Administration', 'Systems Administration', 60, 3, NOW(), NOW()),
('Windows System Administration', 'Systems Administration', 63, 4, NOW(), NOW()),
('Container Networking', 'Networking', 60, 1, NOW(), NOW()),
('TCP/IP Networking', 'Networking', 58, 2, NOW(), NOW()),
('Docker Network Configuration', 'Networking', 66, 3, NOW(), NOW()),
('YAML Configuration', 'Scripting & Automation', 70, 1, NOW(), NOW()),
('Git', 'Scripting & Automation', 55, 2, NOW(), NOW()),
('GitHub Deployment Workflows', 'Scripting & Automation', 52, 3, NOW(), NOW()),
('HTML', 'Software & Applications', 60, 4, NOW(), NOW()),
('PHP', 'Software & Applications', 55, 5, NOW(), NOW()),
('MySQL/MariaDB', 'Databases & Data', 58, 1, NOW(), NOW()),
('Database Troubleshooting', 'Databases & Data', 56, 2, NOW(), NOW()),
('Raspberry Pi', 'Hardware & Infrastructure', 62, 1, NOW(), NOW()),
('Home Server Infrastructure', 'Hardware & Infrastructure', 75, 2, NOW(), NOW()),
('AI Development Environment Setup', 'Software & Applications', 58, 6, NOW(), NOW()),
('Self-Hosted Applications', 'Systems Administration', 76, 5, NOW(), NOW()),
('Nextcloud', 'Software & Applications', 68, 7, NOW(), NOW()),
('Home Assistant', 'Software & Applications', 60, 8, NOW(), NOW()),
('Plex', 'Software & Applications', 60, 9, NOW(), NOW()),
('Jellyfin', 'Software & Applications', 60, 10, NOW(), NOW()),
('Troubleshooting and Log Analysis', 'Systems Administration', 72, 6, NOW(), NOW());
